name: botswana
version: 0.0.1
summary: Run any bot on any chat, painlessly!
description: Coming soon...

grade: devel
confinement: strict

apps:
    # TODO stop/restart bots with process-control
    authorize:
        command: env LC_ALL=C authorize.sh
    deploy:
        command: env LC_ALL=C deploy.sh
        plugs: [home]
    letloose:
        command: env PATH=$PATH:$SNAP LC_ALL=C letloose.sh
        plugs: [home, network, network-bind, system-observe]
    observe:
        command: env LC_ALL=C observe.sh
        plugs: [system-observe]

parts:
    node:
        plugin: nodejs
        node-engine: 6.9.4
        node-packages:
            - yo@1.8.5
            - generator-hubot@0.4.0
        install: ./bin/install.sh
        stage:
            - chatbot
            - bin
            - lib
        prime:
            - chatbot
            - bin
            - lib

    scripts:
        plugin: dump
        source: bin/
        organize:
            authorize.sh: bin/authorize.sh
            common_functions.sh: bin/common_functions.sh
            deploy.sh: bin/deploy.sh
            letloose.sh: bin/letloose.sh
            observe.sh: bin/observe.sh
        stage-packages:
            - bash
            - coreutils
            - libc-bin
            - python
            - python3
        prime:
            - bin
            - usr

