name: botswana
version: 0.0.1
summary: Run any bot on any chat, painlessly!
description: Coming soon...

grade: devel
confinement: strict

apps:
    letloose:
        command: env PATH=$PATH:$SNAP LC_ALL=C letloose.sh
        plugs: [network, network-bind]
    observe:
        command: env LC_ALL=C observe.sh

parts:
    node:
        plugin: nodejs
        node-engine: 6.9.4
        node-packages:
            - yo@1.8.5
            - generator-hubot@0.4.0
        install: ./bin/install.sh
        stage:
            - chatbot
            - bin
            - lib
        prime:
            - chatbot
            - bin
            - lib

    scripts:
        plugin: dump
        source: bin/
        organize:
            letloose.sh: bin/letloose.sh
            observe.sh: bin/observe.sh
        prime:
            - bin

